#!/usr/bin/env npx tsx
// generate-e2e-env.ts - Write a .env file that points a language's E2E test
// at Grafana Cloud's OTLP ingestion endpoint, using the ingest token.
//
// Reads GRAFANA_CLOUD_OTLP_ENDPOINT / GRAFANA_CLOUD_OTLP_INSTANCE_ID /
// GRAFANA_CLOUD_INGEST_TOKEN from the environment (source
// tools/validation/grafana/.env first) — never prints the token; only
// writes it, base64-encoded inside a Basic Auth header, into the target
// file (created with owner-only permissions).
//
// Usage:
//   set -a && source tools/validation/grafana/.env && set +a
//   npx tsx tools/validation/grafana/generate-e2e-env.ts <output-path> <service-name>
//
// Example (from repo root):
//   npx tsx tools/validation/grafana/generate-e2e-env.ts \
//     typescript/test/e2e/company-lookup/.env.grafana-cloud \
//     sovdev-test-company-lookup-typescript-grafana-cloud
//
// The output file is a sibling of the UIS .env, never a replacement for it —
// run-test.sh accepts --env-file so you can point at this without touching
// .env at all:
//   bash run-test.sh --env-file .env.grafana-cloud

import { writeFileSync } from 'node:fs';
import path from 'node:path';

function main(): void {
  const [outputPath, serviceName] = process.argv.slice(2);
  if (!outputPath || !serviceName) {
    console.error('Usage: npx tsx generate-e2e-env.ts <output-path> <service-name>');
    process.exit(1);
  }

  const endpoint = process.env.GRAFANA_CLOUD_OTLP_ENDPOINT;
  const instanceId = process.env.GRAFANA_CLOUD_OTLP_INSTANCE_ID;
  const token = process.env.GRAFANA_CLOUD_INGEST_TOKEN;
  if (!endpoint || !instanceId || !token) {
    console.error(
      'Missing GRAFANA_CLOUD_OTLP_ENDPOINT / GRAFANA_CLOUD_OTLP_INSTANCE_ID / GRAFANA_CLOUD_INGEST_TOKEN — source tools/validation/grafana/.env first',
    );
    process.exit(1);
  }

  const authHeader = Buffer.from(`${instanceId}:${token}`).toString('base64');

  // OTEL_EXPORTER_OTLP_HEADERS is the standard OpenTelemetry format —
  // comma-separated key=value pairs (the W3C Baggage HTTP header format),
  // NOT JSON. The OTel SDK reads this exact env var natively.
  //
  // The value MUST be quoted here: "Authorization=Basic <token>" contains a
  // space, and bash's `source` (used by run-test.sh) word-splits unquoted
  // values on spaces — everything after the space becomes a separate shell
  // word, silently truncating the actual token. This is a different bug
  // than the old JSON-quoting issue (no JSON here at all), but the same
  // root cause: an unquoted value containing a space breaks under `source`.
  // Confirmed empirically: without quotes, the exporters got a 401
  // "no credentials provided" — the Authorization header was truncated to
  // just "Authorization=Basic" with the real token silently dropped.
  const content = `# Generated by tools/validation/grafana/generate-e2e-env.ts
# DO NOT COMMIT — contains a real credential. Already covered by this
# directory's .gitignore (.env.* pattern), but double-check before staging.
#
# Does NOT touch .env — run-test.sh accepts --env-file, use it instead of
# overwriting your local UIS config:
#   bash run-test.sh --env-file ${path.basename(outputPath)}

OTEL_SERVICE_NAME=${serviceName}
OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=${endpoint}/v1/logs
OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=${endpoint}/v1/metrics
OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=${endpoint}/v1/traces
OTEL_EXPORTER_OTLP_HEADERS="Authorization=Basic ${authHeader}"
OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
LOG_TO_FILE=true
LOG_TO_CONSOLE=true
`;

  writeFileSync(path.resolve(outputPath), content, { mode: 0o600 });
  console.log(`✅ Wrote ${outputPath} (contains a real credential — not printed here)`);
}

main();
