"""
GENERATED FILE - DO NOT EDIT.

Generated by specification/tools/generate-field-constants.py from specification/schemas/log-entry-schema.json.
Regenerate after any schema change:
    python3 specification/tools/generate-field-constants.py --lang python
"""


class FieldNames:
    """File-log field names, exactly as they appear in log-entry-schema.json."""

    TIMESTAMP = "timestamp"
    LEVEL = "level"
    MESSAGE = "message"
    SERVICE_NAME = "service_name"
    SERVICE_VERSION = "service_version"
    PEER_SERVICE = "peer_service"
    SESSION_ID = "session_id"
    FUNCTION_NAME = "function_name"
    LOG_TYPE = "log_type"
    TRACE_ID = "trace_id"
    SPAN_ID = "span_id"
    EVENT_ID = "event_id"
    INPUT_JSON = "input_json"
    RESPONSE_JSON = "response_json"
    EXCEPTION_TYPE = "exception_type"
    EXCEPTION_MESSAGE = "exception_message"
    EXCEPTION_STACKTRACE = "exception_stacktrace"
