#!/usr/bin/env python3
"""
Sovdev Logger - Field Name Constant Generator

Reads specification/schemas/log-entry-schema.json's `properties` object --
the single source of truth for file-log field names -- and emits a
per-language constants module. Prevents the field-*naming* bug class
(typos, dots-vs-underscores, camelCase slips) at the point where it
historically originated: an LLM hand-retyping field names from prose into
a new language implementation.

Does not cover value bugs (e.g. `str(enum)` returning the wrong string) or
completeness bugs (a field never added at all) -- both remain the job of
compare-with-master.sh. See:
  website/docs/ai-developer/plans/backlog/PLAN-004-schema-driven-field-generation.md

Usage:
    python3 generate-field-constants.py --lang python
    python3 generate-field-constants.py --lang typescript
    python3 generate-field-constants.py --lang python --check
    python3 generate-field-constants.py --lang python --output /custom/path.py
"""

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SCHEMA_PATH = REPO_ROOT / "specification" / "schemas" / "log-entry-schema.json"

DEFAULT_OUTPUT = {
    "python": REPO_ROOT / "python" / "src" / "field_names.py",
    "typescript": REPO_ROOT / "typescript" / "src" / "fieldNames.ts",
}

GENERATOR_REL_PATH = "specification/tools/generate-field-constants.py"
SCHEMA_REL_PATH = "specification/schemas/log-entry-schema.json"


def load_field_names():
    """Read the schema's `properties` keys, in declaration order."""
    with open(SCHEMA_PATH, "r", encoding="utf-8") as f:
        schema = json.load(f)
    return list(schema["properties"].keys())


def constant_name(field_name):
    """Deterministic field_name -> CONSTANT_NAME. No per-field hardcoding."""
    return field_name.upper()


def render_python(field_names):
    lines = [
        '"""',
        "GENERATED FILE - DO NOT EDIT.",
        "",
        f"Generated by {GENERATOR_REL_PATH} from {SCHEMA_REL_PATH}.",
        "Regenerate after any schema change:",
        f"    python3 {GENERATOR_REL_PATH} --lang python",
        '"""',
        "",
        "",
        "class FieldNames:",
        '    """File-log field names, exactly as they appear in log-entry-schema.json."""',
        "",
    ]
    for field in field_names:
        lines.append(f'    {constant_name(field)} = "{field}"')
    lines.append("")
    return "\n".join(lines)


def render_typescript(field_names):
    lines = [
        "/**",
        " * GENERATED FILE - DO NOT EDIT.",
        " *",
        f" * Generated by {GENERATOR_REL_PATH} from {SCHEMA_REL_PATH}.",
        " * Regenerate after any schema change:",
        f" *     python3 {GENERATOR_REL_PATH} --lang typescript",
        " */",
        "",
        "export const FieldNames = {",
    ]
    for field in field_names:
        lines.append(f"  {constant_name(field)}: '{field}',")
    lines.append("} as const;")
    lines.append("")
    return "\n".join(lines)


RENDERERS = {
    "python": render_python,
    "typescript": render_typescript,
}


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--lang", required=True, choices=sorted(RENDERERS.keys()), help="Target language")
    parser.add_argument("--output", type=Path, default=None, help="Override the default output path")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 0 if the checked-in file matches what regeneration would produce; exit 1 otherwise. Does not write.",
    )
    args = parser.parse_args()

    field_names = load_field_names()
    rendered = RENDERERS[args.lang](field_names)
    output_path = args.output or DEFAULT_OUTPUT[args.lang]

    if args.check:
        if not output_path.exists():
            print(f"MISSING: {output_path} does not exist -- run without --check to generate it.", file=sys.stderr)
            sys.exit(1)
        current = output_path.read_text(encoding="utf-8")
        if current != rendered:
            print(f"STALE: {output_path} does not match {SCHEMA_REL_PATH}. Regenerate it.", file=sys.stderr)
            sys.exit(1)
        print(f"OK: {output_path} matches {SCHEMA_REL_PATH} ({len(field_names)} fields).")
        sys.exit(0)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(rendered, encoding="utf-8")
    print(f"Wrote {len(field_names)} field-name constants to {output_path}")


if __name__ == "__main__":
    main()
