import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Auto-generated from the docs/ folder structure — add a doc, it shows up
// in the sidebar. Reach for a manually curated array (see the noclickops
// or devcontainer-toolbox website/sidebars.ts for examples) once the docs
// tree grows complex enough to need custom ordering or grouping.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
